config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index] do
    get 'page(/:page)', action: :index, on: :collection
  end

  resources :emails, only: [:create] do
    collection do
      get 'compose/:users', action: :compose, as: :compose
      post 'bulk_compose'
    end
  end

  devise_scope :user do
    authenticated :user do
      root 'users#index', as: :root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get '*path', to: 'application#raise_not_found'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email

  include ActiveModel::Model

  attr_accessor :recipients, :subject, :body, :users, :sender

  validates :sender, presence: true
  validates :users, presence: true

  def recipients
    User.email_for_ids(self.users)
  end

  def users=(values)
    @users = User.where(id: values).pluck(:id).compact
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, length: { maximum: 80 }

  scope :all_except, ->(user) { where.not(id: user.id) }
  scope :email_for_ids, ->(ids) { where(id: ids).compact.pluck(:email) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from ActionController::RoutingError, with: :not_found

  def raise_not_found
    raise ActionController::RoutingError.new("No route matches #{params[:path]}")
  end

  def not_found
    flash[:alert] = "The page you are looking for does not exist"
    redirect_to :root
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :password_confirmation, :current_password])
  end

end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController

  before_action :authenticate_user!
  before_action :validate_recipients, only: [:compose, :bulk_compose]
  before_action :initialise_email, only: [:compose, :bulk_compose]

  def compose
  end

  def bulk_compose
    render 'compose'
  end

  def create
    @email = Email.new(email_params)
    @email.sender = current_user.email

    if @email.valid?
      UserMailer.send_mail(@email).deliver
       flash[:notice] = "Email has been sent"
    else
      flash[:error] = "Email can not be sent"
    end
    redirect_to :root
  end

  private

  def validate_recipients
    @recipients = User.where(id: params[:users])
    return redirect_to :root, alert: 'Please select some valid Recipient' if @recipients.blank?
  end

  def initialise_email
    @email = Email.new
  end

  def email_params
    params.require(:email).permit(:subject, :body, users: [])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @users = User.all_except(current_user).page(params[:page]).per(params[:limit])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def titleize(value)
    value.to_s.titleize
  end

  def alert_class(alert_type)
    {
      success: 'success',
      error: 'danger',
      alert: 'warning',
      notice: 'success',
    } [alert_type.to_sym]
  end

end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def pagination_list
    [10, 15, 20, 25, 50, 100]
  end

  def selected_limit(params)
    params[:limit] || Kaminari.config.default_per_page
  end

end

app/views/layouts/_flash.html.erb
<div class='clearfix'></div>
<% flash.each do |type, messages| %>
  <div class='alert alert-<%= alert_class(type) %> alert-dismissible fade in'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <% if messages.present? and messages.is_a? Array %>
      <% messages.each do |message| %>
        <li><%= message.to_s %></li>
      <% end %>
    <% else %>
      <li><%= messages %></li>
    <% end %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="copyright">Copyright <%= Time.now.year %></div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path do %>
        <i class="fa fa-envelope" aria-hidden="true"></i>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MailGenerator</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class='container'>
      <div class='row'>
        <div class='off-canvas-container'>
          <div class='main-content'>
            <%= render 'layouts/flash' %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/index.html.erb
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <h1>Users</h1>
  <hr>
</div>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="col-xs-12 col-sm-6 col-md-10 col-lg-10">
    <%= paginate @users %>
  </div>

  <div class="col-xs-12 col-sm-6 col-md-2 col-lg-2 pull-right record-selector">
    <%= form_tag users_path, method: :get, id: 'users-limit-form' do %>
      <%= select_tag :limit, options_for_select(pagination_list, selected: selected_limit(params)), class: "form-control"  %>
      <div>users per page</div>
    <% end %>
  </div>

  <div class="clearfix"></div>

  <%= form_tag bulk_compose_emails_path, method: :post do %>
    <div class="table-responsive">
      <table class="table table-stretched table-striped table-hover ">
        <thead>
          <th>
            <label class="fancy-checkbox bulk-label">
              <%= check_box_tag 'bulk_tag', 'yes', false, class: 'toggle-in-bulk' %>
              <span></span>
            </label>
          </th>
          <th>Name</th>
          <th>Email</th>
          <th>Action</th>
        <thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <label class="fancy-checkbox">
                  <%= check_box_tag "users[]", '0', false, class: 'users-checkbox' %>
                  <span></span>
                  <%= hidden_field_tag "user", user.id, class: 'user-id' %>
                </label>
              </td>
              <td><%= titleize(user.name) %></td>
              <td><%= user.email %></td>
              <td><%= link_to 'Compose Mail', compose_emails_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= submit_tag 'Bulk Send', class: 'bulk-compose btn btn-primary pull-right', disabled: true %>
  <% end %>
  <%= paginate @users %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name), class: "btn btn-success margin-top-10" %>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-primary margin-top-10" %>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: "btn btn-default margin-top-10" %>
<% end -%>